### ISSUE TITLE
AttributeError: `np.complex_` was removed in the NumPy 2.0 release. Use `np.complex128` instead. when importing image

### ISSUE THREAD

**Issue by gbene** [gecos-lab/DOMStudioImage#1]
Hi!

I was trying to use the script but by using the "environment.yml" the following error is thrown when uploading an image:

```python
Traceback (most recent call last):
  File "/home/gabriele/STORAGE/projects/DOMStudioImage/main.py", line 1712, in load_image
    self.shearlet_system = EdgeSystem(*self.img.shape)
  File "/home/gabriele/STORAGE/projects/DOMStudioImage/coshrem/shearletsystem.py", line 438, in __init__
    self.shearlets = np.zeros((self.rows, self.cols, self.n_shearlets), dtype=np.complex_)
  File "/home/gabriele/miniconda3/envs/domstudioimagetest/lib/python3.9/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.complex_` was removed in the NumPy 2.0 release. Use `np.complex128` instead.
Aborted (core dumped)
``` 

It looks like a version problem with the coshrem local module. I was able to fix the problem by changing the numpy version in the environment.yml to `"numpy<2"`. After this quick fix everything seem to work!

**Comment by waqashussain117** [comment]
Ok thank you. I will do it
